export enum REASON_FOR_COMPENSATION_CHANGE_PERMISSIONS {
  REASON_FOR_COMPENSATION_CHANGE_VIEW = 'REASON_FOR_COMPENSATION_CHANGE_VIEW',
  REASON_FOR_COMPENSATION_CHANGE_WRITE = 'REASON_FOR_COMPENSATION_CHANGE_WRITE',
}
