export const PAYMENT_SETTINGS_LIST_KEY = 'PAYMENT_SETTINGS_LIST';
export const PAYMENT_SETTINGS_ONE_KEY = 'PAYMENT_SETTINGS_ONE_KEY';
export const PAYMENT_METHOD_LIST_KEY = 'PAYMENT_METHOD_LIST_KEY';
export const PAYMENT_METHOD_ONE_KEY = 'PAYMENT_METHOD_ONE_KEY';
