export const COUPON_LIST_KEY = 'COUPON_LIST';
export const COUPON_ONE_KEY = 'COUPON_ONE_KEY';

export const COUPON_PRODUCTS_RULE_LIST_KEY = 'COUPON_PRODUCTS_RULE_LIST_KEY';

export const COUPON_CATEGORY_RULE_LIST_KEY = 'COUPON_CATEGORY_RULE_LIST_KEY';

export const ROTATION_PRODUCTS_LIST_KEY = 'ROTATION_PRODUCTS_LIST_KEY';

export const COUPON_ACTIVITY_KEY = 'COUPON_ACTIVITY_KEY';
