export enum STOCK_ERROR {
  NOT_RELATION_PROVIDER_COMMISSION = 'NOT_RELATION_PROVIDER_COMMISION',

  IMPORT_STOCK_FILE_ERROR = 'SE001',
}

export const PRODUCT_STOCK_ERRORS = {
  [STOCK_ERROR.IMPORT_STOCK_FILE_ERROR]: {
    description: 'stock:errors.IMPORT_STOCK_FILE_ERROR',
  },
};
