stages:
  - build
  - notify
    
build:
  rules:
    - if: $CI_COMMIT_BRANCH == "dev"
      variables:
        environment: 'DEV'
  stage: build
  image: public.ecr.aws/t6x8x3a9/tuambia-node:14.17.3
  script:
    - echo "$ENV_PROD" > ./.env
    - cat ./.env
    - npm cache clean --force
    - npm config set registry "http://nexus.dofleinisoftware.com/repository/npm/"
    - npm config get registry
    - yarn --update-checksums && yarn install
    - export NODE_OPTIONS=--max-old-space-size=8000
    - export NODE_OPTIONS=--max_old_space_size=8000
    - CI= yarn build
    - version=`date +%s`
    - echo "sed 's/.chunk.js/.chunk.js?v="$version"/g' -i build/index.html" | sh
    - cat build/index.html  
    - |
      VERSION=`cat package.json | grep version | head -1 | awk -F: '{ print $$2 }' | sed 's/[", ]//g'`
      DAY=`date +%F"T"%H:%M:%S`
      mkdir -p build/static/js/
      echo '{"version":"'$VERSION'","updatedAt":"'$DAY'"}' > build/static/js/meta.json
      cat build/static/js/meta.json
    - echo "$config_kubernetes" > config_kubernetes
    - export KUBECONFIG=config_kubernetes
    - | 
      if [ "$BUCKET" ]; then   
        aws s3 rm --recursive s3://$BUCKET/
        aws s3 cp --recursive build/ s3://$BUCKET/
        aws cloudfront create-invalidation --distribution-id $CLOUDFRONT --paths "/*"
      fi
    - | 
      if [ "$MINIO_URL" ]; then 
        mc alias set miniotest $MINIO_URL $MINIO_USER $MINIO_PASS --insecure
        mc rm --recursive --force miniotest/$MINIO_BUCKET/ --insecure        
        mc cp --recursive build/  miniotest/$MINIO_BUCKET/ --insecure 
      fi
    - echo $DEPLOYED | bash
    - echo "DEPLOYED SUCCESSFULLY"
  tags:
    - JenkinsAgent
  environment:
    name: $environment

success:
  image: 
    name: ruby:2.5
  stage: notify
  script:
    - echo "curl -i -X GET \"https://api.telegram.org/bot5289978777:AAHaa9Ur7hxtXvAy04yryHXS6CkD1iIKuno/sendMessage?chat_id=-704686534&text=✅✅✅The '"$CI_PROJECT_URL"/-/tree/"$CI_COMMIT_BRANCH"' job execution was successful, for details go to '"$CI_PROJECT_URL"/-/pipelines/"$CI_PIPELINE_ID"' \"" | sh

failure:
  image: 
    name: ruby:2.5
  stage: notify
  when: on_failure
  script:
    - echo "curl -i -X GET \"https://api.telegram.org/bot5289978777:AAHaa9Ur7hxtXvAy04yryHXS6CkD1iIKuno/sendMessage?chat_id=-704686534&text=🚨🚨🚨The '"$CI_PROJECT_URL"/-/tree/"$CI_COMMIT_BRANCH"' job execution has failed, for details go to '"$CI_PROJECT_URL"/-/pipelines/"$CI_PIPELINE_ID"' \"" | sh