export enum ORDER_STATUS_TYPES {
  CREATED = 'CREATED',
  COMPLETED = 'COMPLETED',
  VALIDATED = 'VALIDATED',
  ERROR = 'ERROR',
  ENDED = 'ENDED',
  CANCELED = 'CANCELED',
  PENDING = 'PENDING',
  PENDING_PAYMENT = 'PENDING_PAYMENT',
  PENDING_REFUNDED = 'PENDING_REFUNDED',
  REFUNDED = 'REFUNDED',
  CUSTOM = 'CUSTOM',
}
