export const TAGS_DEFAULT = [
  'Nuevo',
  'Más Vendido',
  'Oferta',
  'Descuento',
  'Edición Limitada',
  'Exclusivo',
  'Popular',
  'Recomendado',
  'Eco-Friendly',
  'Orgánico',
  'Sin Gluten',
  'Vegano',
  'Hecho a Mano',
  'Importado',
  'Nacional',
  'Premium',
  'Alta Calidad',
  'Innovador',
  'Clásico',
  'Moderno',
  'De Temporada',
  'Liquidación',
  'Disponible Pronto',
  'En Stock',
  'Personalizable',
  'Paquete',
  'Regalo',
  'Últimas Unidades',
  'Más Valorado',
  'Fácil de Usar',
  'Garantía Incluida',
  'Sostenible',
  'Edición Especial',
  'Diseño Único',
  'Edición de Colección',
  'Mejor Precio',
  'Compra Rápida',
  '2x1',
  'Promoción',
  'Edición Aniversario',
];

export const onTagsMap = (tags: string[]) => {
  const data = tags?.map((tag) => ({ value: tag }));
  return data;
};
