export const INVENTORY_PERMISSIONS = [
  'PRODUCT_VIEW',
  'PRODUCT_WRITE',
  'PRODUCT_PRICE',
  'LOGISTIC_PROVIDER_VIEW',
  'LOGISTIC_PROVIDER_WRITE',
  'MANUFACTURE_VIEW',
  'MANUFACTURE_WRITE',
  'SUPPLIER_PROVIDER_VIEW',
  'SUPPLIER_PROVIDER_WRITE',
  'STOCK_VIEW',
  'STOCK_WRITE',
  'STORE_VIEW',
  'STORE_WRITE',
  'CATEGORY_VIEW',
  'CATEGORY_WRITE',
  'INVENTORY_REDUCTION_CAUSES_VIEW',
  'INVENTORY_REDUCTION_CAUSES_WRITE',
  'PRODUCT_OFFER_VIEW',
  'PRODUCT_OFFER_WRITE',
  'STOCK_CAUSE_VIEW',
  'STOCK_CAUSE_WRITE',
  'STORE_AREA_VIEW',
  'STORE_AREA_WRITE',
  'TAG_VIEW',
  'TAG_WRITE',
];

export const SALES_PERMISSIONS = [
  'CAUSES_INCIDENCE_VIEW',
  'CAUSES_INCIDENCE_WRITE',
  'COUPON_VIEW',
  'COUPON_WRITE',
  'OFFER_ORDER_VIEW',
  'OFFER_ORDER_WRITE',
  'ORDER_STATUS_VIEW',
  'ORDER_STATUS_WRITE',
  'SHIPPING_PLACE_VIEW',
  'SHIPPING_PLACE_WRITE',
  'HIPPING_HOME_VIEW',
  'HIPPING_HOME_WRITE',
];

export const CLIENT_USERS_PERMISSIONS = [
  'WISH_LIST_VIEW',
  'WISH_LIST_WRITE',
  'REVIEW',
  'REVIEWS_ANALYTICS',
  'DISALLOWED_WORDS_VIEW',
  'DISALLOWED_WORDS_WRITE',
];

export const CONTENT_PERMISSIONS = [
  'BANNERS_VIEW',
  'BANNERS_WRITE',
  'COLLECTIONS_VIEW',
  'COLLECTIONS_WRITE',
  'CONTENT_VIEW',
  'CONTENT_WRITE',
  'MEDIA_VIEW',
  'MEDIA_WRITE',
  'NAVIGATION_VIEW',
  'NAVIGATION_WRITE',
  'TESTIMONY_VIEW',
  'TESTIMONY_WRITE',
];

export const REPORTS_PERMISSIONS = ['ROLE_REPORT', 'ROLE_PROVIDER_REPORT', 'ANALYTICS_USER', 'PRODUCT_ANALYTICS'];

export const SECURITY_PERMISSIONS = [
  'ROLE_VIEW',
  'ROLE_WRITE',
  'ROLES_ASSIGN',
  'ROLE_PROVIDER_VIEW',
  'ROLE_PROVIDER_WRITE',
  'ROLES_PROVIDER_ASSIGN',
  'USER_VIEW',
  'PROVIDER_USER_VIEW',
  'USER_WRITE',
  'USER_INVITE_VIEW',
  'USER_INVITE_WRITE',
];
