export enum COLLECTION_CONTENT_TYPE {
  BANNER = 'BANNER',
  PRODUCT = 'PRODUCT',
  TESTIMONY = 'TESTIMONY',
  CATEGORY = 'CATEGORY',
}

export enum COLLECTION_BANNER_TYPE {
  SIMPLE_BANNER = 'SIMPLE_BANNER',
  MULTI_BANNER = 'MULTI_BANNER',
  SIDE_BY_SIDE_BANNER = 'SIDE_BY_SIDE_BANNER',
}

export enum COLLECTION_BANNERS_POSITION {
  FREE = 'FREE',
  HOME_TOP = 'HOME_TOP',
  HOME_SECOND_BANNER = 'HOME_SECOND_BANNER',
  HOME_THIRD_BANNER = 'HOME_THIRD_BANNER',
  HOME_FOURTH_BANNER = 'HOME_FOURTH_BANNER',
  HOME_FIFTH_BANNER = 'HOME_FIFTH_BANNER',
}

export enum COLLECTION_PRODUCTS_POSITION {
  FREE = 'FREE',
  HOME_FIRST_PRODUCTS = 'HOME_FIRST_PRODUCTS',
  HOME_SECOND_PRODUCTS = 'HOME_SECOND_PRODUCTS',
  HOME_THIRD_PRODUCTS = 'HOME_THIRD_PRODUCTS',
  HOME_FOURTH_PRODUCTS = 'HOME_FOURTH_PRODUCTS',
}

export enum DYNAMIC_COLLECTION_TYPE {
  CUSTOM = 'CUSTOM',
  MOST_RECENT = 'MOST_RECENT',
  MOST_VOTED = 'MOST_VOTED',
  MOST_SOLD = 'MOST_SOLD',
  OFFER_PRODUCTS = 'OFFER_PRODUCTS',
  RECOMMENDED = 'RECOMMENDED',
}

export const COLLECTION_BANNER_TYPE_COLOR = {
  [COLLECTION_BANNER_TYPE.SIMPLE_BANNER]: '#37AEFF',
  [COLLECTION_BANNER_TYPE.MULTI_BANNER]: '#02B389',
  [COLLECTION_BANNER_TYPE.SIDE_BY_SIDE_BANNER]: '#FF9F1C',
};

export const DYNAMIC_COLLECTION_TYPE_COLORS: { [key in DYNAMIC_COLLECTION_TYPE]: string } = {
  [DYNAMIC_COLLECTION_TYPE.MOST_RECENT]: '#3498db',
  [DYNAMIC_COLLECTION_TYPE.MOST_VOTED]: '#f1c40f',
  [DYNAMIC_COLLECTION_TYPE.MOST_SOLD]: '#2ecc71',
  [DYNAMIC_COLLECTION_TYPE.OFFER_PRODUCTS]: '#e74c3c',
  [DYNAMIC_COLLECTION_TYPE.RECOMMENDED]: '#9b59b6',
  [DYNAMIC_COLLECTION_TYPE.CUSTOM]: '#95a5a6',
};

export const POSITION_COLLECTION_COLORS: {
  [key in COLLECTION_BANNERS_POSITION | COLLECTION_PRODUCTS_POSITION]: string;
} = {
  [COLLECTION_BANNERS_POSITION.FREE]: '#54B316', // Verde azulado
  [COLLECTION_BANNERS_POSITION.HOME_FIFTH_BANNER]: '#254EDB', // Naranja oscuro
  [COLLECTION_BANNERS_POSITION.HOME_FOURTH_BANNER]: '#1AADD1', // Púrpura
  [COLLECTION_BANNERS_POSITION.HOME_SECOND_BANNER]: '#B79D00', // Naranja quemado
  [COLLECTION_BANNERS_POSITION.HOME_THIRD_BANNER]: '#c0392b', // Rojo oscuro
  [COLLECTION_BANNERS_POSITION.HOME_TOP]: '#95a5a6', // Gris azulado
  [COLLECTION_PRODUCTS_POSITION.HOME_FIRST_PRODUCTS]: '#2c3e50', // Azul oscuro
  [COLLECTION_PRODUCTS_POSITION.HOME_SECOND_PRODUCTS]: '#c0392b', // Morado oscuro
  [COLLECTION_PRODUCTS_POSITION.HOME_THIRD_PRODUCTS]: '#16a085', // Verde esmeralda
  [COLLECTION_PRODUCTS_POSITION.HOME_FOURTH_PRODUCTS]: '#254EDB', // Azul fuerte
};

export const collectionContentTypeOptions = Object.entries(COLLECTION_CONTENT_TYPE);

export const dynamicTypeOptions = Object.entries(DYNAMIC_COLLECTION_TYPE);

export type COLLECTION_POSITION = COLLECTION_BANNERS_POSITION | COLLECTION_PRODUCTS_POSITION;
export type COLLECTION_DYNAMIC = COLLECTION_BANNERS_POSITION | COLLECTION_PRODUCTS_POSITION;

/* define path route by contentType */
export const COLLECTION_ROUTER: Record<COLLECTION_CONTENT_TYPE, string> = {
  [COLLECTION_CONTENT_TYPE.BANNER]: 'banners',
  [COLLECTION_CONTENT_TYPE.PRODUCT]: 'products',
  [COLLECTION_CONTENT_TYPE.CATEGORY]: 'categories',
  [COLLECTION_CONTENT_TYPE.TESTIMONY]: 'testimonials',
};

export const getContentTypeKeyByValue = (value: string): COLLECTION_CONTENT_TYPE | undefined => {
  const entries = Object.entries(COLLECTION_ROUTER) as Array<[COLLECTION_CONTENT_TYPE, string]>;
  for (const [key, val] of entries) {
    if (val === value) {
      return key;
    }
  }
  return undefined;
};
