export enum REPORTS_PERMISSIONS {
  ROLE_REPORT = 'ROLE_REPORT',
  ROLE_PROVIDER_REPORT = 'ROLE_PROVIDER_REPORT',
  // ANALYTICS_USER = 'ANALYTICS_USER',
  PRODUCT_ANALYTICS = 'PRODUCT_ANALYTICS',
  USER_ANALYTICS = 'USER_ANALYTICS',
}
