export enum PRODUCT_PERMISSIONS {
  PRODUCT_VIEW = 'PRODUCT_VIEW',
  PRODUCT_WRITE = 'PRODUCT_WRITE',
  PRODUCT_PRICE = 'PRODUCT_PRICE',
}

export enum PRODUCT_OFFER_PERMISSIONS {
  VIEW = 'PRODUCT_OFFER_VIEW',
  WRITE = 'PRODUCT_OFFER_WRITE',
}
