export const PRODUCT_LIST_KEY = 'PRODUCT_LIST';
export const PRODUCT_ONE_KEY = 'PRODUCT_ONE_KEY';
export const PRODUCT_PROVIDER_LIST_KEY = 'PRODUCT_PROVIDER_LIST_KEY';
export const PRODUCTS_STORE_LIST_KEY = 'PRODUCTS_STORE_LIST_KEY';
export const PRODUCTS_CATEGORY_LIST_KEY = 'PRODUCTS_CATEGORY_LIST_KEY';
