export const PRODUCT_LIST_KEY = 'PRODUCT_LIST';
export const PRODUCT_ONE_KEY = 'PRODUCT_ONE_KEY';
export const PRODUCT_PROVIDER_LIST_KEY = 'PRODUCT_PROVIDER_LIST_KEY';
export const PRODUCTS_WAREHOUSE_LIST_KEY = 'PRODUCTS_WAREHOUSE_LIST_KEY';
export const PRODUCTS_DISTRIBUTION_CENTER_LIST_KEY = 'PRODUCTS_DISTRIBUTION_CENTER_LIST_KEY';
export const PRODUCTS_CATEGORY_LIST_KEY = 'PRODUCTS_CATEGORY_LIST_KEY';
export const PRODUCTS_STORE_STOCK = 'PRODUCTS_STORE_STOCK';

export const PRODUCTS_STORE_STOCK_CAUSES_LIST_KEY = 'PRODUCTS_STORE_STOCK_CAUSES_LIST_KEY';

export const PRODUCTS_RATE_LIST = 'PRODUCTS_RATE_LIST';
