export enum CONCILIATION_ADJUSTMENT_CAUSES_PERMISSIONS {
  CONCILIATION_ADJUSTMENT_CAUSES_VIEW = 'CONCILIATION_ADJUSTMENT_CAUSES_VIEW',
  CONCILIATION_ADJUSTMENT_CAUSES_WRITE = 'CONCILIATION_ADJUSTMENT_CAUSES_WRITE',
}
