export const ANALYTICS_LIST_KEY = 'ANALYTICS_LIST';
export const ANALYTICS_GENERAL_KEY = 'ANALYTICS_GENERAL_KEY';
export const ANALYTICS_SUMMARY_GENERAL_KEY = 'ANALYTICS_SUMMARY_GENERAL_KEY';
export const ANALYTICS_AGE_GENERAL_KEY = 'ANALYTICS_AGE_GENERAL_KEY';
export const ANALYTICS_POSITION_GENERAL_KEY = 'ANALYTICS_POSITION_GENERAL_KEY';
export const ANALYTICS_CATEGORY_GENERAL_KEY = 'ANALYTICS_CATEGORY_GENERAL_KEY';
export const ANALYTICS_LOCATION_GENERAL_KEY = 'ANALYTICS_LOCATION_GENERAL_KEY';
export const ANALYTICS_TEAM_GENERAL_KEY = 'ANALYTICS_TEAM_GENERAL_KEY';
