export const REPORT_PRODUCT_STOCK_SUMMARY = 'REPORT_PRODUCT_STOCK_SUMMARY';
export const REPORT_PRODUCT_STOCK_ACTIVITY_HISTOGRAM = 'REPORT_PRODUCT_STOCK_ACTIVITY_HISTOGRAM';
export const REPORT_PRODUCT_STOCK_ACTIVITY_TOP_USER = 'REPORT_PRODUCT_STOCK_ACTIVITY_TOP_USER';
export const REPORT_PRODUCT_STOCK_ACTIVITY_REDUCTION = 'REPORT_PRODUCT_STOCK_ACTIVITY_REDUCTION';
export const REPORT_PRODUCT_STOCK_ACTIVITY = 'REPORT_PRODUCT_STOCK_ACTIVITY';
