export const ADDRESS_CURRENCY_LIST_KEY = 'ADDRESS_CURRENCY_LIST';
export const ADDRESS_STATE_LIST_KEY = 'ADDRESS_STATE_LIST';
export const ADDRESS_CITY_LIST_KEY = 'ADDRESS_CITY_LIST';
export const ADDRESS_ADDRESS1_LIST_KEY = 'ADDRESS_ADDRESS1_LIST';
export const ADDRESS_ADDRESS2_LIST_KEY = 'ADDRESS_ADDRESS2_LIST';

export const ADDRESS_STATE_ONE_KEY = 'ADDRESS_STATE_ONE';
export const ADDRESS_CITY_ONE_KEY = 'ADDRESS_CITY_ONE';
export const ADDRESS_ADDRESS1_ONE_KEY = 'ADDRESS_ADDRESS1_ONE';
export const ADDRESS_ADDRESS2_ONE_KEY = 'ADDRESS_ADDRESS2_LIST';
