export enum ADVERTISEMENTS_TYPES {
  WARNING = 'WARNING',
  INFORMATION = 'INFORMATION',
  SUCCESS = 'SUCCESS',
  ALERT = 'ALERT',
}

export const ADVERTISEMENTS_TYPES_VALUES = Object.values(ADVERTISEMENTS_TYPES);
