export enum ADVERTISEMENTS_AUDIENCE {
  ALL = 'ALL',
  ADMINS = 'ADMINS',
  TEAMS = 'TEAMS',
  SPECIFIC = 'SPECIFIC',
}

export const ADVERTISEMENTS_AUDIENCE_VALUES = Object.values(
  ADVERTISEMENTS_AUDIENCE,
);
