export enum OFFER_TYPE {
  SHIPPING_DISCOUNT = 'SHIPPING_DISCOUNT',
  TOTAL_DISCOUNT = 'TOTAL_DISCOUNT',
  PRODUCT_DISCOUNT = 'PRODUCT_DISCOUNT',
  INCLUDE_PRODUCT = 'INCLUDE_PRODUCT',
}

export enum DISCOUNT_TYPE {
  FREE = 'FREE',
  DISCOUNT = 'DISCOUNT',
}

export enum DISCOUNT_VALUE_TYPE {
  FIXED = 'FIXED',
  PERCENT = 'PERCENT',
}

export enum RULE_OFFER_TYPE {
  AMOUNT = 'AMOUNT',
  PRODUCT = 'PRODUCT',
  CATEGORY = 'CATEGORY',
  ADDRESS = 'ADDRESS',
  USAGE = 'USAGE',
  QUANTITY_ORDERS = 'QUANTITY_ORDERS',
  CATEGORY_PRICE = 'CATEGORY_PRICE',
}

export enum OPERATOR_RULE_OFFER_TYPE {
  EQUAL = 'EQUAL',
  LESS_THAN = 'LESS_THAN',
  GREATER_THAN = 'GREATER_THAN',
  AT_LEAST_ONE = 'AT_LEAST_ONE',
  ALL = 'ALL',
}
