export enum InventoryPermissions {
  // Stock
  STOCK_VIEW = 'STOCK_VIEW',
  STOCK_WRITE = 'STOCK_WRITE',
  STOCK_REDUCTION_CAUSE_VIEW = 'STOCK_REDUCTION_CAUSE_VIEW',
  STOCK_REDUCTION_CAUSE_WRITE = 'STOCK_REDUCTION_CAUSE_WRITE',
  STOCK_CAUSE_VIEW = 'STOCK_CAUSE_VIEW',
  STOCK_CAUSE_WRITE = 'STOCK_CAUSE_WRITE', 
  // Distribution
  DISTRIBUTION_CENTER_VIEW = 'DISTRIBUTION_CENTER_VIEW', 
  DISTRIBUTION_CENTER_WRITE = 'DISTRIBUTION_CENTER_WRITE', 
  // Product
  PRODUCT_VIEW = 'PRODUCT_VIEW', 
  PRODUCT_WRITE = 'PRODUCT_WRITE', 
  PRODUCT_PRICE = 'PRODUCT_PRICE', 
  PRODUCT_OFFER_VIEW = 'PRODUCT_OFFER_VIEW', 
  PRODUCT_OFFER_WRITE = 'PRODUCT_OFFER_WRITE', 
  // Providers
  LOGISTIC_PROVIDER_VIEW = 'LOGISTIC_PROVIDER_VIEW', 
  LOGISTIC_PROVIDER_WRITE = 'LOGISTIC_PROVIDER_WRITE', 
  MANUFACTURE_VIEW = 'MANUFACTURE_VIEW',
  MANUFACTURE_WRITE = 'MANUFACTURE_WRITE',
  SUPPLIER_PROVIDER_VIEW = 'SUPPLIER_PROVIDER_VIEW', 
  SUPPLIER_PROVIDER_WRITE = 'SUPPLIER_PROVIDER_WRITE', 
  // Category
  CATEGORY_VIEW = 'CATEGORY_VIEW', 
  CATEGORY_WRITE = 'CATEGORY_WRITE', 
  // Warehouse
  WAREHOUSE_VIEW = 'WAREHOUSE_VIEW', 
  WAREHOUSE_WRITE = 'WAREHOUSE_WRITE', 
  WAREHOUSE_AREA_VIEW = 'WAREHOUSE_AREA_VIEW', 
  WAREHOUSE_AREA_WRITE = 'WAREHOUSE_AREA_WRITE', 
  WAREHOUSE_SUPPLIER_PROVIDER_VIEW = 'WAREHOUSE_SUPPLIER_PROVIDER_VIEW', 
  WAREHOUSE_SUPPLIER_PROVIDER_WRITE = 'WAREHOUSE_SUPPLIER_PROVIDER_WRITE', 
  // Tag
  TAG_VIEW = 'TAG_VIEW', 
  TAG_WRITE = 'TAG_WRITE', 
  // Analytics
  ANALYTICS_VIEW = 'ANALYTICS_VIEW', 
  ANALYTICS_WRITE = 'ANALYTICS_WRITE', 
  // Coupons
  COUPON_VIEW = 'COUPON_VIEW',
  COUPON_WRITE = 'COUPON_WRITE', 
  // Offers
  OFFER_ORDER_VIEW = 'OFFER_ORDER_VIEW', 
  OFFER_ORDER_WRITE = 'OFFER_ORDER_WRITE',
}

export enum SalesPermissions {
  CAUSES_INCIDENCE_VIEW = 'CAUSES_INCIDENCE_VIEW',
  CAUSES_INCIDENCE_WRITE = 'CAUSES_INCIDENCE_WRITE',
  COUPON_VIEW = 'COUPON_VIEW',
  COUPON_WRITE = 'COUPON_WRITE',
  OFFER_ORDER_VIEW = 'OFFER_ORDER_VIEW',
  OFFER_ORDER_WRITE = 'OFFER_ORDER_WRITE',
  ORDER_STATUS_VIEW = 'ORDER_STATUS_VIEW',
  ORDER_STATUS_WRITE = 'ORDER_STATUS_WRITE',
  SHIPPING_PLACE_VIEW = 'SHIPPING_PLACE_VIEW',
  SHIPPING_PLACE_WRITE = 'SHIPPING_PLACE_WRITE',
  HIPPING_HOME_VIEW = 'HIPPING_HOME_VIEW',
  HIPPING_HOME_WRITE = 'HIPPING_HOME_WRITE',
}

export enum ClientUsersPermissions {
  WISH_LIST_VIEW = 'WISH_LIST_VIEW',
  WISH_LIST_WRITE = 'WISH_LIST_WRITE',
  REVIEW = 'REVIEW',
  REVIEWS_ANALYTICS = 'REVIEWS_ANALYTICS',
  DISALLOWED_WORDS_VIEW = 'DISALLOWED_WORDS_VIEW',
  DISALLOWED_WORDS_WRITE = 'DISALLOWED_WORDS_WRITE',
}

export enum ContentPermissions {
  BANNERS_VIEW = 'BANNERS_VIEW',
  BANNERS_WRITE = 'BANNERS_WRITE',
  COLLECTIONS_VIEW = 'COLLECTIONS_VIEW',
  COLLECTIONS_WRITE = 'COLLECTIONS_WRITE',
  CONTENT_VIEW = 'CONTENT_VIEW',
  CONTENT_WRITE = 'CONTENT_WRITE',
  MEDIA_VIEW = 'MEDIA_VIEW',
  MEDIA_WRITE = 'MEDIA_WRITE',
  NAVIGATION_VIEW = 'NAVIGATION_VIEW',
  NAVIGATION_WRITE = 'NAVIGATION_WRITE',
  TESTIMONY_VIEW = 'TESTIMONY_VIEW',
  TESTIMONY_WRITE = 'TESTIMONY_WRITE',
}

export enum ReportsPermissions {
  ROLE_REPORT = 'ROLE_REPORT',
  ROLE_PROVIDER_REPORT = 'ROLE_PROVIDER_REPORT',
  ANALYTICS_USER = 'ANALYTICS_USER',
  PRODUCT_ANALYTICS = 'PRODUCT_ANALYTICS',
}

export enum SecurityPermissions {
  ROLE_VIEW = 'ROLE_VIEW',
  ROLE_WRITE = 'ROLE_WRITE',
  ROLES_ASSIGN = 'ROLES_ASSIGN',
  ROLE_PROVIDER_VIEW = 'ROLE_PROVIDER_VIEW',
  ROLE_PROVIDER_WRITE = 'ROLE_PROVIDER_WRITE',
  ROLES_PROVIDER_ASSIGN = 'ROLES_PROVIDER_ASSIGN',
  USER_VIEW = 'USER_VIEW',
  PROVIDER_USER_VIEW = 'PROVIDER_USER_VIEW',
  USER_WRITE = 'USER_WRITE',
  USER_INVITE_VIEW = 'USER_INVITE_VIEW',
  USER_INVITE_WRITE = 'USER_INVITE_WRITE',
  ADMIN = 'ADMIN',
}
