export enum IncidenceActionType {
  CUSTOMER_CHARGES = 'customer-charges',
  BILLS = 'bills',
  REIMBURSEMENTS = 'reimbursements',
}

export enum INCIDENCE_ACTION_ENUM {
  CONTACT_CUSTOMER = 'CONTACT_CUSTOMER',
  CONTACT_RESPONSIBLE = 'CONTACT_RESPONSIBLE',
  CONTACT_RECIPIENT = 'CONTACT_RECIPIENT',
}

export enum INCIDENCE_SOLUTION_ENUM {
  REIMBURSEMENTS = 'REIMBURSEMENTS',
  REPLACE = 'REPLACE',
  EXCHANGE = 'EXCHANGE',
  COMPENSATION = 'COMPENSATION',
}

export const INCIDENCE_ACTIONS_VALUES = Object.values(INCIDENCE_ACTION_ENUM);
export const INCIDENCE_SOLUTIONS_VALUES = Object.values(INCIDENCE_SOLUTION_ENUM);
