export enum IncidenceActionType {
  CUSTOMER_CHARGES = 'customer-charges',
  BILLS = 'bills',
  REIMBURSEMENTS = 'reimbursements',
}

export enum INCIDENCE_ACTION_ENUM {
  CONTACT_CUSTOMER = 'CONTACT_CUSTOMER',
  CONTACT_RESPONSIBLE = 'CONTACT_RESPONSIBLE',
  CONTACT_RECIPIENT = 'CONTACT_RECIPIENT',
}

export const INCIDENCE_ACTIONS_VALUES = Object.values(INCIDENCE_ACTION_ENUM);
