export enum DELIVERY_TIME_TYPE_ENUM {
  REGULAR = 'REGULAR',
  SCHEDULED = 'SCHEDULED',
  EXPRESS = 'EXPRESS',
}

export enum SHIPPING_TYPE_ENUM {
  HOME_DELIVERY = 'HOME_DELIVERY',
  STORE_PICKUP = 'STORE_PICKUP',
}

export enum DELIVERY_MAX_TIME_ENUM {
  LATE = 'LATE',
  TIME = 'TIME',
  RISK = 'RISK',
  SEVERE = 'SEVERE',
  CRITICS = 'CRITICS',
}
