export enum DELIVERY_TIME_TYPE_ENUM {
  REGULAR = 'REGULAR',
  SCHEDULED = 'SCHEDULED',
  EXPRESS = 'EXPRESS',
}

export enum SHIPPING_TYPE_ENUM {
  HOME_DELIVERY = 'HOME_DELIVERY',
  STORE_PICKUP = 'STORE_PICKUP',
}

export enum DELIVERY_MAX_TIME_ENUM {
  LATE = 'LATE',
  TIME = 'TIME',
  RISK = 'RISK',
  SEVERE = 'SEVERE',
  CRITICS = 'CRITICS',
}

export enum DISCOUNT_OFFER_TYPE {
  OFFER = 'OFFER',
  COUPON = 'COUPON',
}

export enum ORDER_TYPE_ENUM {
  PAID_ORDER = 'PAID_ORDER',
  PRE_ORDER = 'PRE_ORDER',
}

export enum DELIVERY_STATUS_ENUM {
  ON_TIME = 'ON_TIME',
  AT_RISK = 'AT_RISK',
  DELAYED = 'DELAYED',
  SEVERELY_DELAYED = 'SEVERELY_DELAYED',
}
