export enum DELIVERY_TIME_TYPE_ENUM {
  REGULAR = 'REGULAR',
  SCHEDULED = 'SCHEDULED',
  EXPRESS = 'EXPRESS',
}

export enum SHIPPING_TYPE_ENUM {
  HOME_DELIVERY = 'HOME_DELIVERY',
  STORE_PICKUP = 'STORE_PICKUP',
}
