export enum ORDER_PERMISSIONS {
  ORDER_VIEW = 'ORDER_VIEW',
  ORDER_WRITE = 'ORDER_WRITE',
  VIEW_PAYMENT_INFO = 'ORDER_VIEW_PAYMENT_INFO',
  VIEW_CUSTOMER_INFO = 'ORDER_VIEW_CUSTOMER_INFO',
  ORDER_STATUS_WRITE = 'ORDER_STATUS_WRITE',
  ORDER_STATUS_VIEW = 'ORDER_STATUS_VIEW',

  // todo
  ORDER_VALIDATE = 'ORDER_VALIDATE',
}
