export const EMPLOYEES_LIST_KEY = 'EMPLOYEES_LIST';

export const EMPLOYEES_DISEASES_LIST_KEY = 'EMPLOYEES_DISEASES_LIST_KEY';
export const EMPLOYEES_ALLERGIES_LIST_KEY = 'EMPLOYEES_ALLERGIES_LIST_KEY';
export const EMPLOYEES_ONE_KEY = 'EMPLOYEES_ONE_KEY';
