import "../css/globals.css";
import type { Metadata } from "next";
import localFont from "next/font/local";
import DataFlowBackground from "@/components/utils/CyberBackground";
import Section from "@/components/containers/section";
import { ThemeProvider } from "@/components/theme-provider";

const lekton = localFont({
  src: [
    {
      path: "../fonts/Lekton-Bold.ttf",
      weight: "600",
      style: "normal",
    },
    {
      path: "../fonts/Lekton-Italic.ttf",
      weight: "400",
      style: "italic",
    },
    {
      path: "../fonts/Lekton-Regular.ttf",
      weight: "400",
      style: "normal",
    },
  ],
  variable: "--font-lekton",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${lekton.variable} antialiased  font-lekton`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Section>
            {children}
          </Section>
          <DataFlowBackground />
        </ThemeProvider>
      </body>
    </html>
  );
}
