import { PRODUCT_FEATURE_TYPE_ENUM } from '../interfaces/IProductFeature';

export const PRODUCT_FEATURE_TYPES: Record<string, PRODUCT_FEATURE_TYPE_ENUM> = {
  STRING: PRODUCT_FEATURE_TYPE_ENUM.STRING,
  NUMBER: PRODUCT_FEATURE_TYPE_ENUM.NUMBER,
  BOOLEAN: PRODUCT_FEATURE_TYPE_ENUM.BOOLEAN,
  DATE: PRODUCT_FEATURE_TYPE_ENUM.DATE,
  ARRAY: PRODUCT_FEATURE_TYPE_ENUM.ARRAY,
  COLOR: PRODUCT_FEATURE_TYPE_ENUM.COLOR,
};
