export const EMPLOYEE_LIST_KEY = 'EMPLOYEE_LIST';
export const EMPLOYEE_ONE_KEY = 'EMPLOYEE_ONE_KEY';

export const EMPLOYEE_JOB_INFORMATION_LIST_KEY = 'EMPLOYEE_JOB_INFORMATION_LIST';

export const EMPLOYEE_COMPENSATION_LIST_KEY = 'EMPLOYEE_COMPENSATION_LIST_KEY';

export const EMPLOYEE_CATEGORY_LIST_KEY = 'EMPLOYEE_CATEGORY_LIST_KEY';

export const EMPLOYEE_RULE_LIST_KEY = 'EMPLOYEE_RULE_LIST_KEY';

export const EMPLOYEE_RULE_TYPES_LIST_KEY = 'EMPLOYEE_RULE_TYPES_LIST_KEY';

export const EMPLOYEE_TIME_OFF_STATS_KEY = 'EMPLOYEE_TIME_OFF_STATS_KEY';
export const EMPLOYEE_TIME_OFF_LIST_KEY = 'EMPLOYEE_TIME_OFF_LIST_KEY';
