export const TIME_OFF_POLICIES_LIST_KEY = 'TIME_OFF_POLICIES_LIST_KEY';

export const TIME_OFF_POLICY_KEY = 'TIME_OFF_POLICY_KEY';

export const TIME_OFF_POLICY_TYPES_LIST_KEY = 'TIME_OFF_POLICY_TYPES_LIST_KEY';

export const TIME_OFF_POLICY_TYPE_KEY = 'TIME_OFF_POLICY_TYPE_KEY';
