export enum AUDIT_LOG_COLORS {
  CREATE = '#7AD15B57',
  UPDATE = '#D0ECFF',
  REMOVE = '#F848423D',
  REMOVE_MANY = '#F848423D',
  RESTORE = '#873476',
}

export enum AUDIT_LOG_MODULE_ENUM {
  SUPPLIER = 'SUPPLIER',
}

export enum AUDIT_LOG_EVENT_ENUM {
  UPDATE = 'UPDATE',
  CREATE = 'CREATE',
  REMOVE = 'REMOVE',
  RESTORE = 'RESTORE',
  REMOVE_MANY = 'REMOVE_MANY',
}
