export enum AUDIT_LOG_COLORS {
  CREATE = '#7AD15B',
  UPDATE = '#D0ECFF',
  UPLOAD_FILE = '#bef2c2',
  REMOVE = '#F84842',
  DELETED = '#F84842',
  REMOVE_MANY = '#F84842',
  RESTORE = '#873476',
}

export enum AUDIT_LOG_MODULE_ENUM {
  SUPPLIER = 'SUPPLIER',
  SEO_ROBOT_MODULE = 'SEO_ROBOT_MODULE',
  SEO_STATIC_PAGES_MODULE = 'SEO_STATIC_PAGES_MODULE',
}

export enum AUDIT_LOG_EVENT_ENUM {
  UPDATE = 'UPDATE',
  CREATE = 'CREATE',
  REMOVE = 'REMOVE',
  RESTORE = 'RESTORE',
  REMOVE_MANY = 'REMOVE_MANY',
  UPLOAD_FILE = 'UPLOAD_FILE',
  DELETED = 'DELETED',
}
