export enum AUDIT_LOG_MODULE_ENUM {
  SUPPLIER = 'SUPPLIER',
  SEO_ROBOT_MODULE = 'SEO_ROBOT_MODULE',
  SEO_STATIC_PAGES_MODULE = 'SEO_STATIC_PAGES_MODULE',
}

export enum AUDIT_LOG_EVENT_ENUM {
  UPDATE = 'UPDATE',
  CREATE = 'CREATE',
  REMOVE = 'REMOVE',
  RESTORE = 'RESTORE',
  REMOVE_MANY = 'REMOVE_MANY',
  UPLOAD_FILE = 'UPLOAD_FILE',
  DELETED = 'DELETED',

  UPDATE_SHIPPING_INFO = 'UPDATE_SHIPPING_INFO',
  UPDATE_SHIPPING_TIME = 'UPDATE_SHIPPING_TIME',
  UPDATE_SCORE = 'UPDATE_SCORE',
  UPDATE_RULES = 'UPDATE_RULES',
  UPDATE_MEDIA = 'UPDATE_MEDIA',
  UPDATE_SEO = 'UPDATE_SEO',
  UPDATE_PROVIDERS = 'UPDATE_PROVIDERS',
}

export const AUDIT_LOG_EVENT_COLOR: { [key in AUDIT_LOG_EVENT_ENUM]: string } = {
  [AUDIT_LOG_EVENT_ENUM.UPDATE]: '#116F34',
  [AUDIT_LOG_EVENT_ENUM.CREATE]: '#1976D2',
  [AUDIT_LOG_EVENT_ENUM.REMOVE]: '#D32F2F',
  [AUDIT_LOG_EVENT_ENUM.RESTORE]: '#fcc40a',
  [AUDIT_LOG_EVENT_ENUM.REMOVE_MANY]: '#D32F2F',
  [AUDIT_LOG_EVENT_ENUM.UPLOAD_FILE]: '#004D66',
  [AUDIT_LOG_EVENT_ENUM.DELETED]: '#D32F2F',
  [AUDIT_LOG_EVENT_ENUM.UPDATE_SHIPPING_INFO]: '#7B1FA2',
  [AUDIT_LOG_EVENT_ENUM.UPDATE_SHIPPING_TIME]: '#5D4037',
  [AUDIT_LOG_EVENT_ENUM.UPDATE_SCORE]: '#C2185B',
  [AUDIT_LOG_EVENT_ENUM.UPDATE_RULES]: '#455A64',
  [AUDIT_LOG_EVENT_ENUM.UPDATE_MEDIA]: '#06738C',
  [AUDIT_LOG_EVENT_ENUM.UPDATE_SEO]: '#28A540',
  [AUDIT_LOG_EVENT_ENUM.UPDATE_PROVIDERS]: '#3E12AB',
};

export const AUDIT_LOG_COLORS_TEXT: { [key in AUDIT_LOG_EVENT_ENUM]: string } = {
  [AUDIT_LOG_EVENT_ENUM.UPDATE]: '#FFF',
  [AUDIT_LOG_EVENT_ENUM.CREATE]: '#FFF',
  [AUDIT_LOG_EVENT_ENUM.REMOVE]: '#FFF',
  [AUDIT_LOG_EVENT_ENUM.RESTORE]: '#FFF',
  [AUDIT_LOG_EVENT_ENUM.REMOVE_MANY]: '#FFF',
  [AUDIT_LOG_EVENT_ENUM.UPLOAD_FILE]: '#FFF',
  [AUDIT_LOG_EVENT_ENUM.DELETED]: '#FFF',
  [AUDIT_LOG_EVENT_ENUM.UPDATE_SHIPPING_INFO]: '#FFF',
  [AUDIT_LOG_EVENT_ENUM.UPDATE_SHIPPING_TIME]: '#FFF',
  [AUDIT_LOG_EVENT_ENUM.UPDATE_SCORE]: '#FFF',
  [AUDIT_LOG_EVENT_ENUM.UPDATE_RULES]: '#FFF',
  [AUDIT_LOG_EVENT_ENUM.UPDATE_MEDIA]: '#FFF',
  [AUDIT_LOG_EVENT_ENUM.UPDATE_SEO]: '#FFF',
  [AUDIT_LOG_EVENT_ENUM.UPDATE_PROVIDERS]: '#FFF',
};
