export enum WAREHOUSE_PERMISSIONS {
  WAREHOUSE_VIEW = 'WAREHOUSE_VIEW',
  WAREHOUSE_WRITE = 'WAREHOUSE_WRITE',
  WAREHOUSE_SUPPLIER_PROVIDER_VIEW = 'WAREHOUSE_SUPPLIER_PROVIDER_VIEW',
  WAREHOUSE_SUPPLIER_PROVIDER_WRITE = 'WAREHOUSE_SUPPLIER_PROVIDER_WRITE',
}
