export const WAREHOUSES_LIST_KEY = 'WAREHOUSES_LIST';
export const WAREHOUSES_ONE_KEY = 'WAREHOUSES_ONE_KEY';
export const WAREHOUSES_PRODUCT_LIST_KEY = 'WAREHOUSES_PRODUCT_LIST_KEY';
export const WAREHOUSES_PROVIDER_SUPPLIER_LIST_KEY = 'WAREHOUSES_PROVIDER_SUPPLIER_LIST_KEY';
